"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,Play,Pause,Camera,Square,Download,RotateCcw} from 'lucide-react';
import {androidBridge,saveToAndroid} from '@/lib/android';
import {DEFAULT_VIDEO_POSE,paintVideo,recordCanvas,waitForVideoFrame,type VideoPose} from '@/lib/video-tools';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {toast,Toaster} from 'sonner';
type Asset={url:string;name:string;kind:'video'|'image';duration:number;native?:boolean};
export function VideoWorkspace({onBack}:{onBack:()=>void}){
 const [mode,setMode]=useState<'camera'|'compare'>('camera'),[view,setView]=useState<'overlay'|'side'>('overlay');
 const [old,setOld]=useState<Asset|null>(null),[current,setCurrent]=useState<Asset|null>(null),[alpha,setAlpha]=useState(40),[pose,setPose]=useState<VideoPose>({...DEFAULT_VIDEO_POSE});
 const [devices,setDevices]=useState<MediaDeviceInfo[]>([]),[deviceId,setDeviceId]=useState(''),[zoom,setZoom]=useState(1),[zoomRange,setZoomRange]=useState({min:1,max:1,step:.01}),[cameraDimensions,setCameraDimensions]=useState('');
 const zoomQueue=useRef<number|null>(null),zoomRunning=useRef(false);
 const [cameraReady,setCameraReady]=useState(false),[facing,setFacing]=useState<'environment'|'user'>('environment'),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[offset,setOffset]=useState(0);
 const [recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[includeOverlay,setIncludeOverlay]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{url:string;blob:Blob}|null>(null);
 const canvas=useRef<HTMLCanvasElement>(null),liveVideo=useRef<HTMLVideoElement>(null),oldVideo=useRef<HTMLVideoElement>(null),newVideo=useRef<HTMLVideoElement>(null),oldImage=useRef<HTMLImageElement>(null),input=useRef<HTMLInputElement>(null);
 const recordingCanvas=useRef<HTMLCanvasElement|null>(null),stream=useRef<MediaStream|null>(null),recorder=useRef<ReturnType<typeof recordCanvas>|null>(null),pick=useRef<'old-video'|'old-image'|'current'>('old-video'),nativePick=useRef(''),alive=useRef(true),generation=useRef(0),isStarting=useRef(false);
 const config=useRef({mode,view,alpha,pose,includeOverlay,playing,offset,recording});config.current={mode,view,alpha,pose,includeOverlay,playing,offset,recording};
 const stopCamera=useCallback(()=>{generation.current++;isStarting.current=false;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(liveVideo.current)liveVideo.current.srcObject=null;setCameraReady(false);},[]);
 const startCamera=useCallback(async()=>{
  if(isStarting.current||stream.current)return;isStarting.current=true;const token=++generation.current;setError('');
  try{androidBridge()?.stopCamera?.();const value=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},...(deviceId?{deviceId:{exact:deviceId}}:{}),width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30,max:30}},audio:false});
   if(token!==generation.current||!alive.current){value.getTracks().forEach(t=>t.stop());return;}stream.current=value;liveVideo.current!.srcObject=value;await liveVideo.current!.play();if(alive.current&&token===generation.current){setCameraReady(true);const track=value.getVideoTracks()[0],caps=track.getCapabilities() as MediaTrackCapabilities & {zoom?:{min:number;max:number;step:number}},settings=track.getSettings() as MediaTrackSettings & {zoom?:number};setZoomRange(caps.zoom || {min:1,max:1,step:.01});setZoom(settings.zoom ?? 1);setCameraDimensions(`${liveVideo.current!.videoWidth} × ${liveVideo.current!.videoHeight}`);try{const list=await navigator.mediaDevices.enumerateDevices();if(token===generation.current)setDevices(list.filter(d=>d.kind==='videoinput'));}catch{}};
  }catch(e){if(alive.current&&token===generation.current){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setError('Kamera konnte nicht gestartet werden. Prüfe die Kameraberechtigung und versuche es erneut.');}}
  finally{if(token===generation.current)isStarting.current=false;}
 },[facing,deviceId]);
 async function changeZoom(value:number){
  zoomQueue.current=value;setZoom(value);if(zoomRunning.current)return;zoomRunning.current=true;
  try{while(zoomQueue.current!==null){const next=zoomQueue.current;zoomQueue.current=null;const track=stream.current?.getVideoTracks()[0];if(!track)break;
    try{await track.applyConstraints({advanced:[{zoom:next} as MediaTrackConstraintSet]});if(track!==stream.current?.getVideoTracks()[0])break;if(zoomQueue.current===null)setZoom((track.getSettings() as MediaTrackSettings & {zoom?:number}).zoom ?? next);}
    catch{if(track===stream.current?.getVideoTracks()[0]){zoomQueue.current=null;setZoom((track.getSettings() as MediaTrackSettings & {zoom?:number}).zoom ?? 1);setError('Diese Kamera unterstützt den gewählten Zoom nicht.');}}
  }}finally{zoomRunning.current=false;}
 }
 function pause(){oldVideo.current?.pause();newVideo.current?.pause();setPlaying(false);}
 function stopRecording(){recorder.current?.stop();pause();}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;recorder.current?.cancel();stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{if(mode==='camera')void startCamera();else stopCamera();return()=>stopCamera();},[mode,startCamera,stopCamera]);
 useEffect(()=>{const hidden=()=>{if(document.hidden){stopRecording();stopCamera();}},paused=()=>{stopRecording();stopCamera();},resume=()=>{if(config.current.mode==='camera')void startCamera();};document.addEventListener('visibilitychange',hidden);window.addEventListener('zeitblick-pause',paused);window.addEventListener('zeitblick-resume',resume);return()=>{document.removeEventListener('visibilitychange',hidden);window.removeEventListener('zeitblick-pause',paused);window.removeEventListener('zeitblick-resume',resume);};},[startCamera,stopCamera]);
 useEffect(()=>()=>{if(old){if(old.native)androidBridge()?.releaseReference?.(old.url);else URL.revokeObjectURL(old.url);}},[old]);
 useEffect(()=>()=>{if(current)URL.revokeObjectURL(current.url);},[current]);useEffect(()=>()=>{if(result)URL.revokeObjectURL(result.url);},[result]);
 useEffect(()=>{const selected=(e:Event)=>{const d=(e as CustomEvent).detail;if(!String(d?.requestId).startsWith('video-'))return;if(d.requestId!==nativePick.current){if(d.url)androidBridge()?.releaseReference?.(d.url);return;}nativePick.current='';setBusy(false);if(d.error){setError(d.error);return;}if(d.cancelled)return;if(typeof d.url==='string'&&d.url.startsWith('https://appassets.androidplatform.net/reference/')){setOld({url:d.url,name:d.name||'Bildvorlage',kind:'image',duration:0,native:true});setPose({...DEFAULT_VIDEO_POSE});}};window.addEventListener('zeitblick-reference-result',selected);return()=>window.removeEventListener('zeitblick-reference-result',selected);},[]);
 useEffect(()=>{let raf=0,lastUpdate=0,lastDraw=0;const out=document.createElement('canvas');recordingCanvas.current=out;
  function frame(now:number){if(now-lastDraw<30){raf=requestAnimationFrame(frame);return;}lastDraw=now;const c=canvas.current;if(!c){raf=requestAnimationFrame(frame);return;}const cfg=config.current;
   const base=cfg.mode==='camera'?liveVideo.current:newVideo.current,reference=old?.kind==='image'?oldImage.current:oldVideo.current;
   const width=cfg.view==='side'?1920:1080,height=1920;if(c.width!==width||c.height!==height){c.width=width;c.height=height;}
   const ctx=c.getContext('2d')!;ctx.fillStyle='#080d09';ctx.fillRect(0,0,width,height);
   if(cfg.view==='side'){paintVideo(ctx,reference,0,0,width/2,height,1,cfg.pose);paintVideo(ctx,base,width/2,0,width/2,height);}else{paintVideo(ctx,base,0,0,width,height);paintVideo(ctx,reference,0,0,width,height,cfg.alpha/100,cfg.pose);}
   if(cfg.recording){const composite=cfg.mode==='compare'||cfg.includeOverlay;const ow=composite?width:1080;if(out.width!==ow||out.height!==height){out.width=ow;out.height=height;}const oc=out.getContext('2d')!;oc.fillStyle='#080d09';oc.fillRect(0,0,ow,height);if(composite)oc.drawImage(c,0,0);else paintVideo(oc,base,0,0,ow,height);}
   if(cfg.playing&&oldVideo.current&&old?.kind==='video'){
    const t=oldVideo.current.currentTime;if(now-lastUpdate>200){setTime(t);lastUpdate=now;}
    if(cfg.mode==='compare'&&newVideo.current&&Math.abs(newVideo.current.currentTime-(t+cfg.offset))>.18)newVideo.current.currentTime=Math.max(0,t+cfg.offset);
   }
   raf=requestAnimationFrame(frame);
  }raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);recordingCanvas.current=null;};
 },[old,current]);
 const duration=old?.kind==='video'?Math.max(0,mode==='compare'&&current?Math.min(old.duration,current.duration-offset):old.duration):0;
 const start=Math.max(0,-offset);
 function seek(t:number){pause();const value=Math.min(duration,Math.max(mode==='compare'?start:0,t));if(oldVideo.current)oldVideo.current.currentTime=value;if(newVideo.current)newVideo.current.currentTime=Math.max(0,value+offset);setTime(value);}
 async function play(){try{if(old?.kind==='video'&&oldVideo.current){if(oldVideo.current.ended||time>=duration-.05||(mode==='compare'&&oldVideo.current.currentTime<start))seek(mode==='compare'?start:0);await oldVideo.current.play();}if(mode==='compare'&&newVideo.current){newVideo.current.currentTime=Math.max(0,(oldVideo.current?.currentTime||0)+offset);await newVideo.current.play();}setPlaying(true);return true;}catch{pause();setError('Das Video lässt sich nicht abspielen. Bitte ein anderes Video oder Format wählen.');return false;}}
 function choose(target:typeof pick.current){pause();setError('');pick.current=target;if(target==='old-image'&&androidBridge()?.pickReference){const id='video-'+crypto.randomUUID();nativePick.current=id;setBusy(true);androidBridge()!.pickReference!(id);}else{input.current!.accept=target==='old-image'?'image/*':'video/*';input.current!.click();}}
 async function load(file:File){const target=pick.current,url=URL.createObjectURL(file);setBusy(true);setError('');try{
  const kind=target==='old-image'?'image':'video';if(kind==='video'&&file.type&&!file.type.startsWith('video/'))throw Error('Bitte eine Videodatei auswählen.');
  let duration=0;if(kind==='video'){const probe=document.createElement('video');probe.preload='metadata';probe.src=url;try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Video konnte nicht gelesen werden.')),15000);probe.onloadedmetadata=()=>{clearTimeout(timer);resolve();};probe.onerror=()=>{clearTimeout(timer);reject(Error('Videoformat nicht unterstützt. Versuche MP4 mit H.264.'));};});duration=probe.duration;if(!Number.isFinite(duration)||duration<=0)throw Error('Die Videodauer konnte nicht gelesen werden.');}finally{probe.removeAttribute('src');probe.load();}}
  else{const image=new Image();image.src=url;await image.decode();}
  if(!alive.current){URL.revokeObjectURL(url);return;}const asset:Asset={url,name:file.name,kind,duration};if(target==='current')setCurrent(asset);else{setOld(asset);setPose({...DEFAULT_VIDEO_POSE});}setTime(0);setOffset(0);
 }catch(e){URL.revokeObjectURL(url);setError((e as Error).message);}finally{if(alive.current)setBusy(false);}}
 async function record(){
  if(!recordingCanvas.current||recording||busy)return;setBusy(true);setError('');const out=recordingCanvas.current;const composite=mode==='compare'||includeOverlay;out.width=composite?(view==='side'?1920:1080):1080;out.height=1920;
  try{if(old?.kind==='video'&&!(await play()))return;const base=mode==='camera'?liveVideo.current:newVideo.current;if(!base)throw Error('Videoquelle fehlt.');await Promise.all([waitForVideoFrame(base),old?.kind==='video'&&oldVideo.current?waitForVideoFrame(oldVideo.current):old?.kind==='image'&&oldImage.current?oldImage.current.decode():Promise.resolve()]);if(!alive.current||document.hidden)return;const ctx=out.getContext('2d')!,reference=old?.kind==='image'?oldImage.current:oldVideo.current;ctx.fillStyle='#080d09';ctx.fillRect(0,0,out.width,out.height);if(composite&&view==='side'){paintVideo(ctx,reference,0,0,out.width/2,out.height,1,pose);paintVideo(ctx,base,out.width/2,0,out.width/2,out.height);}else{paintVideo(ctx,base,0,0,out.width,out.height);if(composite)paintVideo(ctx,reference,0,0,out.width,out.height,alpha/100,pose);}
   setSeconds(0);config.current.recording=true;setRecording(true);
   recorder.current=recordCanvas(out,blob=>{recorder.current=null;if(!alive.current)return;config.current.recording=false;setRecording(false);pause();setResult({blob,url:URL.createObjectURL(blob)});},message=>{recorder.current=null;if(alive.current){config.current.recording=false;setRecording(false);pause();setError(message);}});
  }catch(e){config.current.recording=false;setRecording(false);pause();setError((e as Error).message);}finally{if(alive.current)setBusy(false);}
 }
 useEffect(()=>{if(!recording)return;const start=Date.now(),timer=setInterval(()=>setSeconds(Math.floor((Date.now()-start)/1000)),250);return()=>clearInterval(timer);},[recording]);
 async function save(){if(!result)return;setBusy(true);try{const ext=result.blob.type.includes('mp4')?'mp4':'webm',file=new File([result.blob],'zeitblick-video-'+Date.now()+'.'+ext,{type:result.blob.type});if(androidBridge())await saveToAndroid([file]);else{const link=document.createElement('a');link.href=result.url;link.download=file.name;link.click();}toast.success('Video gespeichert.');setResult(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const drag=useRef<{x:number;y:number;pose:VideoPose}|null>(null);
 const canRecord=mode==='camera'?cameraReady:!!old&&old.kind==='video'&&!!current&&duration>start;
 return <div className="video-workspace" role="dialog" aria-label="Video"><Toaster theme="dark"/><header className="align-header"><button className="back-button" aria-label="Zur Kamera" disabled={recording||busy} onClick={()=>{if(result)setResult(null);else onBack();}}><ArrowLeft size={22}/></button><h1>Video</h1></header>
  <div className="align-pinned"><button disabled={recording||busy} className={mode==='camera'?'active':''} onClick={()=>{pause();setMode('camera');}}>Filmen</button><button disabled={recording||busy} className={mode==='compare'?'active':''} onClick={()=>{pause();setMode('compare');}}>Videos vergleichen</button></div>
  <main className="video-content"><input ref={input} type="file" className="sr-only" accept="video/*" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void load(f);}}/>
   <fieldset disabled={recording||busy}><div className="video-imports"><button onClick={()=>choose('old-video')}>Altes Video {old?.kind==='video'?'wechseln':'wählen'}</button>{mode==='camera'?<button onClick={()=>choose('old-image')}>Bildvorlage {old?.kind==='image'?'wechseln':'wählen'}</button>:<button onClick={()=>choose('current')}>Neues Video {current?'wechseln':'wählen'}</button>}</div>
   <div className="align-pinned video-view"><button className={view==='overlay'?'active':''} onClick={()=>setView('overlay')}>Overlay</button><button className={view==='side'?'active':''} onClick={()=>setView('side')}>Side by side</button></div></fieldset>
   <div className="video-stage"><canvas ref={canvas} width={1080} height={1920} aria-label="Videovorschau" onPointerDown={e=>{if(recording||!old)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,pose:{...pose}};}} onPointerMove={e=>{const d=drag.current;if(!d)return;const r=e.currentTarget.getBoundingClientRect(),scale=Math.min(r.width/e.currentTarget.width,r.height/e.currentTarget.height),width=e.currentTarget.width*(view==='side'?.5:1);setPose({...d.pose,x:Math.max(-1,Math.min(1,d.pose.x+(e.clientX-d.x)/(width*scale))),y:Math.max(-1,Math.min(1,d.pose.y+(e.clientY-d.y)/(1920*scale)))});}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}/>{recording&&<span className="video-recording">● {seconds} s</span>}</div>
   {error&&<p className="align-error" role="alert">{error}</p>}
   <fieldset disabled={recording||busy} className="video-settings">
    {mode==='camera'&&!cameraReady&&<button className="primary-button" onClick={()=>void startCamera()}><Camera size={18}/> Kamera erneut starten</button>}
    {mode==='camera'&&cameraReady&&<><label>Kamera<select aria-label="Videokamera" value={deviceId || stream.current?.getVideoTracks()[0]?.getSettings().deviceId || ''} onChange={e=>setDeviceId(e.target.value)}>{devices.map((d,i)=><option key={d.deviceId} value={d.deviceId}>{d.label || `Kamera ${i+1}`}</option>)}</select></label><small>Kamera liefert {cameraDimensions} Pixel</small>{zoomRange.max>zoomRange.min?<><label>Kamera-Zoom · {zoom.toFixed(2)}×<input aria-label="Video Kamera-Zoom" type="range" min={zoomRange.min} max={zoomRange.max} step={zoomRange.step || .01} value={zoom} onChange={e=>void changeZoom(+e.target.value)}/></label><div className="zoom-presets">{Array.from(new Set([zoomRange.min,1,2,3,5,10])).filter(z=>z>=zoomRange.min&&z<=zoomRange.max).sort((a,b)=>a-b).map(z=><button key={z} onClick={()=>void changeZoom(z)} aria-pressed={Math.abs(zoom-z)<.02}>{Number(z.toFixed(1))}×</button>)}</div></>:<small>Diese Videokamera stellt keinen stufenlosen Zoom bereit. Versuche eine andere Kamera.</small>}</>}
    {view==='overlay'&&<label>Deckkraft der Vorlage · {alpha} %<input type="range" min={0} max={100} value={alpha} onChange={e=>setAlpha(+e.target.value)}/></label>}
    {old&&<details><summary>Vorlage anpassen</summary><p>Vorlage in der Vorschau mit einem Finger verschieben.</p><label>Größe · {pose.scale.toFixed(2)}×<input type="range" min={.25} max={4} step={.01} value={pose.scale} onChange={e=>setPose({...pose,scale:+e.target.value})}/></label><label>Drehung · {pose.angle}°<input type="range" min={-180} max={180} value={pose.angle} onChange={e=>setPose({...pose,angle:+e.target.value})}/></label><button onClick={()=>setPose({...DEFAULT_VIDEO_POSE})}><RotateCcw size={16}/> Zurücksetzen</button></details>}
    {old?.kind==='video'&&<><label>Zeit · {time.toFixed(1)} / {duration.toFixed(1)} s<input type="range" min={mode==='compare'?Math.min(start,duration):0} max={duration||1} step={.05} value={Math.min(time,duration)} onChange={e=>seek(+e.target.value)}/></label><button disabled={mode==='compare'&&!current} onClick={()=>playing?pause():void play()}>{playing?<Pause size={18}/>:<Play size={18}/>} {playing?'Pause':'Abspielen'}</button></>}
    {mode==='compare'&&<label>Startversatz neues Video (Sekunden)<input type="number" min={-600} max={600} step={.1} value={offset} onChange={e=>{pause();setOffset(Math.max(-600,Math.min(600,Number(e.target.value)||0)));}}/><small>+2: Neues Video beginnt zwei Sekunden später in seiner Datei.</small></label>}
    {mode==='camera'&&<><label className="video-checkbox"><input type="checkbox" checked={includeOverlay} onChange={e=>setIncludeOverlay(e.target.checked)}/> Vorlage / Side by side mit aufnehmen</label><button onClick={()=>{setDeviceId('');setFacing(facing==='environment'?'user':'environment');}}>Front / Rückkamera wechseln</button></>}
   </fieldset>
   <p className="video-note">Full-HD-Ausgabe · ohne Ton · bis 60 Sekunden / 45 MB pro Clip · MP4 oder WebM je nach Gerät. Beim Aufnehmen in der App bleiben.</p>
  </main><footer className="video-footer"><button className="primary-button" disabled={busy||(!recording&&!canRecord)} onClick={()=>recording?stopRecording():void record()}>{recording?<Square size={18}/>:<Camera size={18}/>} {recording?'Aufnahme stoppen':mode==='camera'?'Video aufnehmen':'Vergleich aufnehmen'}</button></footer>
  <div className="video-sources" aria-hidden="true"><video ref={liveVideo} muted playsInline/><video ref={oldVideo} src={old?.kind==='video'?old.url:undefined} muted playsInline preload="auto" onEnded={()=>{stopRecording();pause();}} onError={()=>{if(old?.kind==='video')setError('Das alte Video kann nicht wiedergegeben werden. Versuche MP4 mit H.264.');}}/>{old?.kind==='image'&&<img ref={oldImage} src={old.url} alt=""/>}<video ref={newVideo} src={current?.url} muted playsInline preload="auto" onEnded={()=>{stopRecording();pause();}} onError={()=>{if(current)setError('Das neue Video kann nicht wiedergegeben werden. Versuche MP4 mit H.264.');}}/></div>
  <Dialog open={!!result} onOpenChange={open=>{if(!open&&!busy)setResult(null);}}><DialogContent className="alignment-output" showCloseButton={!busy} onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onPointerDownOutside={e=>{if(busy)e.preventDefault();}}><DialogTitle>Dein Video</DialogTitle><DialogDescription>Prüfen und in der Galerie speichern.</DialogDescription>{result&&<video src={result.url} controls playsInline style={{width:'100%',maxHeight:'50dvh'}}/>}<button className="primary-button" disabled={busy} onClick={()=>void save()}><Download size={18}/>{busy?'Wird gespeichert …':'Video speichern'}</button>{error&&<p role="alert">{error}</p>}</DialogContent></Dialog>
 </div>;
}
